changed QuantConnect.IBAutomater.csproj to SDK style
QuantConnect/IBAutomater pull request #16
Opened 2020-05-11 15:41 UTC by vslee

- it was previously MSBuild style
- this changes it to the newer SDK style, which will allow further options in the future
- SDK style is more concise: a lot of settings which were explicitly specified before are now the defaults
- functional settings have been preserved, including targeting .net framework 4.5.2, as well as Newtonsoft.Json 10.0.3
- App.Config, packages.config, and AssemblyInfo.cs were able to be removed as their information is now in QuantConnect.IBAutomater.csproj
- NuGet settings have not been touched
- part of #15

2020-09-13 19:03 UTC, vslee commented
rebased to master, solving merge conflicts

2020-09-14 18:50 UTC, jaredbroad commented
HI @vslee! Welcome! Thanks for the PR we'll review and try and get it merged today.

2020-09-15 13:03 UTC, StefanoRaggi requested changes
Thank you for the PR @vslee
I just tested the changes and pushed v1.0.30 to NuGet

Just a few minor changes requested:
- remove the `Properties` folder from the project file
- update the demo project to reference the latest NuGet package (v1.0.30)
- update `QuantConnect.IBAutomater.nuspec` for the new build output path:
these are the updated lines:
```
    <version>1.0.30</version>
    ...
    <file src="net452\QuantConnect.IBAutomater.exe" target="lib\net45" />
    <file src="net452\QuantConnect.IBAutomater.pdb" target="lib\net45" />
    ...
    <file src="net452\IBAutomater.bat" target="build" />
    <file src="net452\IBAutomater.sh" target="build" />
```

2020-09-15 13:03 UTC, StefanoRaggi commented on QuantConnect.IBAutomater/QuantConnect.IBAutomater.csproj
> +  </ItemGroup>
I think we can safely remove these lines

2020-09-15 16:33 UTC, StefanoRaggi approved these changes
Thank you for the quick fixes 👍

2020-09-15 16:34 UTC, merged